export const samplePackages = [
  {
    id: 1,
    title: "Kerala Backwater Escape",
    slug: "kerala-backwater-escape",
    destination: "Kerala",
    country: "India",
    category: "Domestic",
    duration: "5 Days / 4 Nights",
    days: 5,
    nights: 4,
    price: 14999,
    originalPrice: 17999,
    shortDescription: "Tea hills, calm backwaters and boutique stays across Munnar and Alleppey.",
    description: "Experience Kerala at an easy, memorable pace with misty plantations, scenic drives, houseboat moments and carefully selected stays.",
    highlights: "Munnar tea gardens\nAlleppey backwater cruise\nPrivate sightseeing\nBreakfast included",
    inclusions: "4 nights accommodation\nDaily breakfast\nPrivate transfers\nSightseeing as per itinerary",
    exclusions: "Airfare\nPersonal expenses\nOptional activities\nAnything not listed in inclusions",
    hotelDetails: "Premium 3-star / 4-star stays with breakfast.",
    transportation: "Private air-conditioned vehicle for transfers and sightseeing.",
    terms: "Rates are subject to availability. Standard cancellation terms apply.",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=85",
    featured: true,
    active: true,
    seoTitle: "Kerala Backwater Escape | Viago",
    seoDescription: "Book a 5-day Kerala holiday with Munnar, Alleppey and curated stays.",
    images: [],
    itineraries: [
      { id: 1, day: 1, title: "Arrive in Kochi", description: "Meet your Viago representative and drive through waterfalls and spice country to Munnar." },
      { id: 2, day: 2, title: "Explore Munnar", description: "Visit tea gardens, viewpoints and the region's most-loved natural attractions." },
      { id: 3, day: 3, title: "Munnar to Alleppey", description: "Scenic transfer to the backwaters with a relaxed evening by the water." },
      { id: 4, day: 4, title: "Backwater experience", description: "Enjoy a houseboat-style cruise and a calm Kerala sunset." },
      { id: 5, day: 5, title: "Departure", description: "Breakfast, checkout and transfer to Kochi for your onward journey." },
    ],
  },
  {
    id: 2,
    title: "Bali Honeymoon Bliss",
    slug: "bali-honeymoon-bliss",
    destination: "Bali",
    country: "Indonesia",
    category: "Honeymoon",
    duration: "6 Days / 5 Nights",
    days: 6,
    nights: 5,
    price: 42999,
    originalPrice: 48999,
    shortDescription: "A romantic Bali escape with Ubud, temples, beaches and private experiences.",
    description: "A romantic itinerary designed for couples who want beautiful stays, relaxed sightseeing and iconic Bali moments without rushing.",
    highlights: "Ubud day tour\nTemple sunset experience\nPrivate transfers\nCouple-friendly stays",
    inclusions: "5 nights accommodation\nBreakfast\nAirport transfers\nSelected sightseeing",
    exclusions: "Flights\nVisa fees\nPersonal expenses\nTravel insurance",
    hotelDetails: "Boutique hotel and private villa combination, subject to availability.",
    transportation: "Private air-conditioned transfers for scheduled tours.",
    terms: "Passport validity and entry requirements are the traveller's responsibility.",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=85",
    featured: true,
    active: true,
    seoTitle: "Bali Honeymoon Package | Viago",
    seoDescription: "Discover a romantic 6-day Bali honeymoon with Ubud, beaches and private transfers.",
    images: [],
    itineraries: [
      { id: 6, day: 1, title: "Welcome to Bali", description: "Airport pickup and a relaxed check-in to begin your honeymoon." },
      { id: 7, day: 2, title: "Ubud highlights", description: "Rice terraces, waterfalls and culture with a private vehicle." },
      { id: 8, day: 3, title: "Leisure day", description: "Slow morning, spa time or optional activities." },
      { id: 9, day: 4, title: "Temple & sunset", description: "Explore a signature temple and enjoy a sunset experience." },
      { id: 10, day: 5, title: "Beach day", description: "Free time for beach clubs, shopping and romantic dining." },
      { id: 11, day: 6, title: "Departure", description: "Checkout and private airport transfer." },
    ],
  },
  {
    id: 3,
    title: "Dubai City & Desert",
    slug: "dubai-city-desert-package",
    destination: "Dubai",
    country: "UAE",
    category: "International",
    duration: "5 Days / 4 Nights",
    days: 5,
    nights: 4,
    price: 37999,
    originalPrice: 41999,
    shortDescription: "A vibrant Dubai break with skyline attractions, a desert safari and shopping time.",
    description: "See the modern icons of Dubai, enjoy an exciting desert safari and keep enough free time to shop and explore your way.",
    highlights: "Dubai city tour\nDesert safari\nDhow cruise\nAirport transfers",
    inclusions: "4 nights stay\nBreakfast\nAirport transfers\nTours listed in itinerary",
    exclusions: "Flights\nVisa unless stated\nTourism taxes\nPersonal expenses",
    hotelDetails: "Centrally located 3-star / 4-star hotel options.",
    transportation: "Shared or private transfers as specified in the final quotation.",
    terms: "Final package price depends on travel dates and room availability.",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=85",
    featured: true,
    active: true,
    seoTitle: "Dubai Holiday Package | Viago",
    seoDescription: "Book a Dubai city and desert holiday with Viago.",
    images: [],
    itineraries: [
      { id: 12, day: 1, title: "Arrive Dubai", description: "Airport transfer and hotel check-in." },
      { id: 13, day: 2, title: "Dubai city tour", description: "Discover modern landmarks and classic neighbourhoods." },
      { id: 14, day: 3, title: "Desert safari", description: "Afternoon desert experience with entertainment and dinner." },
      { id: 15, day: 4, title: "Leisure & shopping", description: "Explore malls, attractions or optional experiences." },
      { id: 16, day: 5, title: "Departure", description: "Checkout and airport transfer." },
    ],
  },
  {
    id: 4,
    title: "Kashmir Valley Retreat",
    slug: "kashmir-valley-retreat",
    destination: "Kashmir",
    country: "India",
    category: "Family",
    duration: "6 Days / 5 Nights",
    days: 6,
    nights: 5,
    price: 26999,
    originalPrice: 30999,
    shortDescription: "Lakes, valleys and mountain views across Srinagar, Gulmarg and Pahalgam.",
    description: "A scenic family-friendly Kashmir journey with comfortable transfers, mountain landscapes and time to enjoy the valley at your own pace.",
    highlights: "Srinagar stay\nGulmarg excursion\nPahalgam valley\nShikara ride",
    inclusions: "5 nights stay\nBreakfast and dinner\nTransfers\nSelected sightseeing",
    exclusions: "Airfare\nGondola tickets\nPony rides\nPersonal expenses",
    hotelDetails: "Comfortable hotels and an optional premium houseboat night.",
    transportation: "Private vehicle for scheduled transfers and sightseeing.",
    terms: "Local transport rules may apply in selected sightseeing zones.",
    image: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1600&q=85",
    featured: false,
    active: true,
    seoTitle: "Kashmir Family Package | Viago",
    seoDescription: "A 6-day Kashmir holiday covering Srinagar, Gulmarg and Pahalgam.",
    images: [],
    itineraries: [],
  },
];

export const destinations = [
  {
    name: "Munnar",
    country: "Kerala",
    subtitle: "Tea gardens & misty hills",
    image:
      "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Alleppey",
    country: "Kerala",
    subtitle: "Backwaters & houseboats",
    image:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Wayanad",
    country: "Kerala",
    subtitle: "Forests, hills & waterfalls",
    image:
      "https://images.unsplash.com/photo-1605537964076-3cb0ea2ff329?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Varkala",
    country: "Kerala",
    subtitle: "Cliffs, beaches & sunsets",
    image:
      "https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Thekkady",
    country: "Kerala",
    subtitle: "Wildlife & spice plantations",
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Kumarakom",
    country: "Kerala",
    subtitle: "Lakeside escapes",
    image:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Athirappilly",
    country: "Kerala",
    subtitle: "Waterfalls & rainforest",
    image:
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=85",
  },
  {
    name: "Kovalam",
    country: "Kerala",
    subtitle: "Beachside holidays",
    image:
      "https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=1200&q=85",
  },
];
